---
version: ~> 1.0

os: linux
dist: bionic

language: ruby

install:
  - sudo apt update --yes
  - sudo apt install ca-certificates
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-redirect --white-list "mvfjfugdwgc5uwho.onion,www.mhprofessional.com,ghostproject.fr,www.zoomeye.org,www.amazon.com,packetstormsecurity.com"
